// vue-exam/src/views/corret_exam_list/index.vue
<script setup lang="ts">
import { getExamHistory } from '@/utils/request';
import Search from './search.vue'
import { onMounted } from 'vue';
import { useExamStore } from '../../stores/exam';
import dayjs from 'dayjs'

const PAGE_COUNT = 10;

const exam_store = useExamStore()

const tableData = [
  {
    created: '2016-05-04',
    is_judge: false,
    subject_name: 'react课程',
    user_name: '詹姆斯'
  },
  {
    created: '2016-05-04',
    is_judge: true,
    subject_name: 'vue课程',
    user_name: '杜兰特'
  },
]

onMounted(async () => {
  const res = await getExamHistory()
  exam_store.exam_list_page_data.count = res.count as number
  exam_store.exam_list = res.data
})

function read_click(row: any) {

}

function corret_click(row: any) {

}

async function page_change(val: any) {
  console.log(val)
  exam_store.exam_list_page_data.current_page = val;

  const res = await getExamHistory({
    ...exam_store.exam_list_page_data.search_params,
    skip: PAGE_COUNT * (val - 1)
  })

  exam_store.exam_list_page_data.count = res.count as number
  exam_store.exam_list = res.data
}

</script>

<template>
  <div>
    <Search />
    <el-table class="table" :data="exam_store.exam_list" style="width: 100%">
      <el-table-column prop="subject_name" label="试卷名称" />
      <el-table-column prop="created" label="考试时间">
        <template #default="scope">
          <span>
            {{ dayjs(scope.row.created).format('YYYY MM-DD hh:mm:ss') }}
          </span>
        </template>
      </el-table-column>
      <el-table-column prop="is_judge" label="是否阅卷">
        <template #default="scope">
          <span :class="{
      red: scope.row.is_judge
    }">
            {{ scope.row.is_judge ? '已阅' : '未阅' }}
          </span>
        </template>
      </el-table-column>
      <el-table-column prop="is_judge" label="操作">
        <!-- vue的缺陷 -->
        <template #default="scope">
          <el-tag :class="{ can_read: true }"
            @click="scope.row.is_judge ? read_click(scope.row) : corret_click(scope.row)"
            :type="scope.row.is_judge ? 'primary' : 'danger'" disable-transitions>{{ scope.row.is_judge ? '查看' : '阅卷'
            }}</el-tag>
        </template>
      </el-table-column>
    </el-table>
    <el-pagination :current-page="exam_store.exam_list_page_data.current_page" @current-change="page_change" background
      layout="prev, pager, next" :total="exam_store.exam_list_page_data.count" />
  </div>
</template>

<style scoped lang="scss">
.can_read {
  cursor: pointer;
}

.red {
  color: red;
}

.table {
  margin-bottom: 20px;
}
</style>

// react-exam/src/pages/corret_exam_list/index.tsx
import React, { FC, useEffect, useState } from 'react'
import { Table, Pagination } from 'antd';
// import { tableDefaultData, tableColumns } from './interface'
import styles from './index.module.css'
import { useAppSelector, useAppDispatch } from '@/store';
import { get_exam_history, select_corret_exam_list_loading, select_exam_history_data, set_exam_list_data } from '../../store/slice/subject';
import { Tag, Space, Badge } from 'antd'
import { useNavigate } from 'react-router';
import dayjs from 'dayjs'
import Search from './search'

const PAGE_COUNT = 10;

function CorretExamList() {
    let exam_list_data = useAppSelector(select_exam_history_data)
    const loading = useAppSelector(select_corret_exam_list_loading)

    // console.log('exam_list',exam_list)
    let exam_list = exam_list_data.list.map((item: any) => {
        return {
            ...item,
            key: item._id
        }
    })

    const dispatch = useAppDispatch()
    const navigate = useNavigate()

    useEffect(() => {
        dispatch(get_exam_history({}))
    }, [])

    function read_exam_click(item: any) {
        if (item.is_judge) {
            const exam_id = item._id
            navigate(`/read_exam/${exam_id}`)
        } else {
            const exam_id = item._id
            navigate(`/corret_exam/${exam_id}`)
        }
    }

    const tableColumns = [{
        title: '试卷名称',
        dataIndex: 'subject_name',
        key: 'subject_name',
    }, {
        title: '学生姓名',
        dataIndex: 'user_name',
        key: 'user_name',
    }, {
        title: '考试时间',
        dataIndex: 'created',
        key: 'created',
        render: (_: any, record: any) => {
            // console.log(_, record)
            return <span>{dayjs(record.created).format('YYYY MM-DD hh:mm:ss')}</span>
        }
    }, {
        title: '是否阅卷',
        dataIndex: 'is_judge',
        key: 'is_judge',
        render: (status: boolean) => {
            const statusObj = !status ? {
                status: 'default',
                text: "未阅卷"
            } : {
                status: 'error',
                text: "已阅卷"
            }
            return (
                <Space>
                    <Badge status={statusObj.status as "default" | "error" | "success" | "processing" | "warning" | undefined} />
                    {statusObj.text}
                </Space>
            )
        }
    }, {
        title: '操作',
        dataIndex: '_id',
        key: '_id',
        render: (row: any, record: any) => {
            return (
                <Tag color={record.is_judge ? 'blue' : 'red'} onClick={() => {
                    read_exam_click(record)
                }} style={{ cursor: 'pointer' }}>
                    {record.is_judge ? "查看" : "阅卷"}
                </Tag>
            )
        },
    }]

    function page_change(count: number) {
        dispatch(set_exam_list_data({
            current_page: count
        }))

        dispatch(get_exam_history({
            ...exam_list_data.search_params,
            skip: PAGE_COUNT * (count - 1)
        }))
    }

    return (
        <div className={styles["exam-history"]}>
            <div className={styles.search_wrap}>
                <Search />
            </div>
            <div className='table-list-wrapper'>
                <Table loading={loading} dataSource={exam_list} columns={tableColumns} pagination={false} />
                <Pagination
                    className={styles.pagenation}
                    pageSize={PAGE_COUNT}
                    current={exam_list_data.current_page}
                    total={exam_list_data.count}
                    onChange={page_change}
                />
            </div>
        </div>
    )
}

export default CorretExamList
