// vue-exam/src/components/layout.vue
<script setup lang="ts">
import { RouterView } from 'vue-router'
import { onMounted, onBeforeMount } from 'vue'
import Header from '@components/header/index.vue';
import Menu from '@components/menu/index.vue'


onBeforeMount(() => {

})

onMounted(async () => {

})
</script>

<template>
  <div class="layout">
    <div class="header_layout">
      <Header />
    </div>

    <div>
      <div className="nav_wrap">
        <Menu />
      </div>
      <RouterView />
    </div>
  </div>
</template>

<style scoped></style>

// react-exam/src/components/layout.tsx
import { Outlet } from "react-router-dom";
import Header from "./header";
import Menu from "./menu";

function Layout() {
    return <div className="layout">
        <div className="header_wrap">
            <Header />
        </div>
        <div className="nav_wrap">
            <Menu />
        </div>
        <div className="outlet_wrap">
            <Outlet />
        </div>
    </div>
};

export default Layout;
