// react-exam/src/page/login/index.tsx
import React, { useEffect, useState } from 'react';
import { Button, Form, Input, message } from 'antd';
import style from './index.module.scss';
import login_desc from './assets/login_desc.png';
import login_logo from './assets/login_logo.png';
import login_title_cn from './assets/login_title_cn.png';
import login_title_en from './assets/login_title_en.png';
import { RoleParams, set_role } from '@/store/slice/role';
import { useDispatch } from 'react-redux';
import axios, { AxiosRes } from '@/utils/https';
import { useNavigate } from 'react-router';
const COUNT = 60
const LoginPage: React.FC = () => {
    const [count, set_count] = useState(0)
    const [form] = Form.useForm()
    const [messageApi, contextHolder] = message.useMessage()
    const navigate = useNavigate()
    const dispatch = useDispatch()
    // 开启倒计时
    useEffect(() => {
        setTimeout(() => {
            if (count === 0) return
            set_count(count - 1)
        }, 1000)
    }, [count])
    //发送验证码
    const startCode = () => {
        if (count !== 0) return
        form.validateFields(['phone']).then(() => {
            set_count(COUNT)
        }).catch(err => {
            console.log(err);
        })
    }
    const onFinishFailed = (errorInfo: any) => {
        console.log('Failed:', errorInfo);
    }
    // 点击登录
    const onLogin = async (values: RoleParams) => {
        const res: AxiosRes = await axios.post('/api/user/login', values)
        if (res.data.code !== 0) return messageApi.warning(res.data.msg)
        dispatch(set_role(res.data.data))
        //根据用户权限跳转至不同的页面
        switch (res.data.data.role) {
            case 'student':
                if (res.data.data.has_person_info) {
                    navigate('/exam_select')
                } else {
                    navigate('/person_info')
                }
                break
            case 'admin':
                navigate('/corret_exam_list')
                break
            case 'super_admin':
                navigate('/corret_exam_list')
                break
        }
    }
    return <div className={style.page_container}>
        {contextHolder}
        <div className={style.login_container}>
            <div className={style.login_left}>
                <div className={style.left_title}><img src={login_desc} alt="" /></div>
            </div>
            <div className={style.login_right}>
                <div className={style.right_title}>
                    <div><img src={login_logo} alt="" /></div>
                    <div className={style.title_container}>
                        <div><img src={login_title_cn} alt="" /></div>
                        <div><img src={login_title_en} alt="" /></div>
                    </div>
                </div>
                <div className={style.right_form}>
                    <Form
                        size='large'
                        labelCol={{ span: 5 }}
                        wrapperCol={{ span: 20 }}
                        onFinish={onLogin}
                        labelAlign='left'
                        onFinishFailed={onFinishFailed}
                        form={form}
                    >
                        <Form.Item
                            label="手机号"
                            name="phone"
                            rules={[{ required: true, message: '请填写手机号' }, { pattern: new RegExp(/^1(3|4|5|6|7|8|9)\d{9}$/, "g"), message: '请输入正确的手机号' }]}
                        >
                            <Input placeholder='请输入手机号' />
                        </Form.Item>
                        <div style={{ 'position': 'relative' }}>
                            <Form.Item
                                label="验证码"
                                name="code"
                                rules={[{ required: true, message: '请输入验证码' }]}
                            >
                                <Input placeholder='请输入验证码' style={{ padding: '7px 100px 7px 11px' }} />
                            </Form.Item>
                            <div className={[style.form_code_btn, count !== 0 ? style.form_code_btn_disabled : ''].join(' ')} onClick={startCode}>{count === 0 ? '获取验证码' : `${count}秒`}</div>
                        </div>
                        <div className={style.form_btn}>
                            <Button type="primary" htmlType="submit">
                                登录
                            </Button>
                        </div>
                    </Form>
                </div>
            </div>
        </div>
    </div>
}

export default LoginPage;

// vue-exam/src/views/login/index.vue
<script setup lang="ts">
import { onMounted, onBeforeMount, reactive, ref } from 'vue';
import login_desc from './assets/login_desc.png'
import login_logo from './assets/login_logo.png'
import login_title_cn from './assets/login_title_cn.png'
import login_title_en from './assets/login_title_en.png'
import { loginPost } from '../../utils/request';
import { useRouter } from 'vue-router';
import { useCommonStore } from '../../stores/common';

// 这个地址会变成，基于项目的相对路径，相对package.json所在的根目录
console.log('login_desc', login_desc)
const router = useRouter()
const form = reactive({
  phone: '',
  code: ''
})

onMounted(async () => {
  // 获取用户信息
})
// 这是可响应的对象
const timer_ob = reactive({
  count: 60,
  show: false
})

async function login() {
  // console.log(form.phone, form.code)
  const res = await loginPost(form)

  if (!res.has_person_info) {
    router.push('/person_info')
  }
}

function get_code() {
  timer_ob.count = 60
  timer_ob.show = true

  let timer = setInterval(() => {
    timer_ob.count--
    if (timer_ob.count === 0) {
      timer_ob.show = false
      clearInterval(timer)
    }
  }, 1000)
}

</script>

<template>
  <div class="page_container">
    <div class="login_container">
      <div class="login_left">
        <div class="left_title">
          <img :src="login_desc" alt="" />
        </div>
      </div>
      <div class="login_right">
        <div class="right_title">
          <div>
            <img :src="login_logo" alt="" />
          </div>
          <div class="title_container">
            <div>
              <img :src="login_title_cn" alt="" />
            </div>
            <div>
              <img :src="login_title_en" alt="" />
            </div>
          </div>
        </div>
        <div class="right_form">
          <el-form :model="form" label-width="60px">
            <el-form-item label="用户名">
              <el-input class="input" size="large" v-model="form.phone" placeholder="请输入phone" />
            </el-form-item>
            <el-form-item label="验证码">
              <el-input class="input" size="large" v-model="form.code" placeholder="请输入验证码">
                <template #append>
                  <el-button v-if="!timer_ob.show" @click="get_code">点击获取验证码</el-button>
                  <el-button v-if="timer_ob.show" :disabled="true">倒计时 {{ timer_ob.count }} s</el-button>
                </template>
              </el-input>
            </el-form-item>
            <el-button @click="login" class="btn" size="large" type="primary">点击登录</el-button>
          </el-form>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped lang="scss">
.input {
  margin-bottom: 20px;
}

.btn {
  width: 100%;
}

.page_container {
  position: relative;
  height: 100vh;
  background: url(./assets/login_bg.png) no-repeat;
  background-size: cover;
  overflow: auto;

  .login_container {
    width: 960px;
    height: 600px;
    background: #EFF5FF;
    border-radius: 16px;
    box-shadow: 0px 2px 16px 0px rgba(235, 239, 243, 0.23);
    display: flex;
    position: relative;
    top: calc(50% - 300px);
    left: calc(50% - 480px);

    .login_left {
      width: 50%;

      .left_title {
        width: 340px;
        height: 380px;
        margin: 87px auto;
      }
    }

    .login_right {
      width: 50%;
      box-sizing: border-box;
      background: #FFFFFF;
      height: 100%;
      padding: 80px 40px 80px 33px;
      border-top-right-radius: 16px;
      border-bottom-right-radius: 16px;

      .right_title {
        display: flex;
        align-items: center;

        .title_container {
          margin-left: 15px;
        }
      }

      .right_form {
        margin-top: 80px;
      }

      a {
        color: #EFF5FF;
      }
    }
  }
}
</style>
