// vue-exam/src/views/student_manage/search.vue
<script setup lang="ts">
import { onMounted, onBeforeMount, reactive } from 'vue';

const form = reactive({
    name: '',
    phone: ''
})

function search() {
    console.log('form', form.name, form.phone)
}

</script>

<template>
    <div>
        <el-form :model="form" label-width="100px" class="form">
            <el-form-item label="名字">
                <el-input class="input" v-model="form.name" placeholder="请输入phone" />
            </el-form-item>
            <el-form-item label="phone">
                <el-input class="input" v-model="form.phone" placeholder="请输入phone" />
            </el-form-item>
            <el-button class="btn" type="primary" @click="search">查询</el-button>
        </el-form>
    </div>
</template>

<style scoped lang="scss">
.form {
    display: flex;

    .btn {
        margin-left: 20px;
    }
}
</style>

// react-exam/src/pages/student_manage/Search.tsx
import { Button, Form, Input, Radio } from 'antd';
import { useAppDispatch, AppDispatch } from '../../store/index';
import { get_student_async, set_student_list_current_page, set_student_list_search_params } from '../../store/slice/user';
import styles from './index.module.css'

function Search() {
    const [form] = Form.useForm();
    const disptch: AppDispatch = useAppDispatch()

    async function search_click() {
        const form_data = await form.validateFields()
        // console.log(form_data)

        Object.keys(form_data).forEach((key: string) => {
            if (!form_data[key]) {
                delete form_data[key]
            }
        })

        disptch(set_student_list_search_params(form_data))
        disptch(set_student_list_current_page(1))
        // await getStudentListRequest(form_data)
        disptch(get_student_async(form_data))
    }

    return (
        <div className={styles.wrap}>
            <Form
                layout='inline'
                form={form}
            >
                <Form.Item label="花名" name="name">
                    <Input placeholder="请输入" />
                </Form.Item>
                <Form.Item label="dianhua" name="phone">
                    <Input placeholder="请输入" />
                </Form.Item>
                <Form.Item>
                    <Button type="primary" onClick={search_click}>查询</Button>
                </Form.Item>
            </Form>
        </div>
    )
}

export default Search;
